name: Lint and Compile

on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11
      - run: pip install flake8
      - run: pip install -e .
